### ISSUE TITLE
Link is hidden when user navs from the homepage

### ISSUE THREAD

**Issue by jermyk** [neontribe/contemplating-action#132] opened 2019-04-02 09:27 UTC
## Description
On https://contemplating-action.herokuapp.com/# a link is visible under the header title
Navigate away from the homepage and the link is hardly visible
![Untitled_Clipping_040219_102643_AM](https://user-images.githubusercontent.com/4446325/55391711-cf3ab380-5531-11e9-9b01-7580e72ef3f6.jpg)

## Platform (if relevant)
What device and browser were you using?
Image was captured in hover state on a Windows 10 laptop.

**Comment by katjam** [comment] 2019-04-02 11:04
Possible dupe of #128

**Comment by katjam** [comment] 2019-04-02 15:47
closing as dupe

**Closed as completed by katjam** 2019-04-02 15:47 UTC
